version: '3'
services:
  app:
    container_name: cow_app
    image: cow-app
    build: .
    ports:
      - 8000:8000
    environment:
      - COW_API_DATABASE_URL=postgresql://username:password@db/cow_db
    depends_on:
      - db
    networks:
      - cow
  db:
    container_name: cow_db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cow_db
    ports:
      - 5432:5432
    networks:
      - cow

networks:
  cow:
    name: "cow_network"
